Added Casino for review
Zievidinov/Travelline_practice pull request #1
Opened 2024-03-29 07:46 UTC by RedkeyD

2024-03-31 18:33 UTC, Nafanyan requested changes
Небольшие придирки по оформлению

2024-03-31 18:33 UTC, Nafanyan commented on Casino/Program.cs
> +
Лишние пробелы

2024-03-31 18:33 UTC, Nafanyan commented on Casino/Program.cs
> +
лишний пробел

2024-03-31 18:33 UTC, Nafanyan commented on Casino/Program.cs
> +
лишний пробел

2024-03-31 18:33 UTC, Nafanyan commented on Casino/Program.cs
> +if ( currentSum > 0 && bet <= currentSum )
а тут лучше поставить пробел, уже другой логический блок)

2024-03-31 18:33 UTC, Nafanyan commented on Casino/Program.cs
> +
лишний пробел)

2024-04-01 01:33 UTC, RedkeyD commented
Все лишние пробелы были убраны)

2024-04-02 05:57 UTC, Nafanyan approved these changes

2024-04-02 10:38 UTC, merged