Added translator for review
Zievidinov/Travelline_practice pull request #2
Opened 2024-03-29 07:47 UTC by RedkeyD

2024-03-31 16:27 UTC, Nafanyan requested changes
В целом хорошо сделано, раскидано на разные классы. Единственное это комменты по оформлению и названиям. Там где поставил dir это скорее придирки и предложения сделать по другому, исправлять не обязательно, на твоё усмотрение)

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/Program.cs
> +
Пустые строки

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/Translator.cs
> +
Пустая строка

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
> +
Пустая строка

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
> +    public void ReadFile( string filePath, Dictionary<string, string> englishToRussianDictionary, Dictionary<string, string> russianToEnglishDictionary )
Если строка очень длинная можно переносить аргументы на следующие строки, тут будет
    public void ReadFile(
        string filePath,
        Dictionary<string, string> englishToRussianDictionary,
        Dictionary<string, string> russianToEnglishDictionary )

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
> +    private void PopulateDictionaries( string[] lines, Dictionary<string, string> englishToRussianDictionary, Dictionary<string, string> russianToEnglishDictionary )
Смотри коммент выше)

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/Program.cs
> +    static void TranslateWord( string wordToTranslate, Dictionary<string, string> englishToRussianDictionary, Dictionary<string, string> russianToEnglishDictionary )
Если строка очень длинная можно переносить аргументы на следующие строки, тут будет
    static void TranslateWord( 
        string wordToTranslate, 
        Dictionary<string, string> englishToRussianDictionary,
        Dictionary<string, string> russianToEnglishDictionary )

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/Program.cs
> +                Console.WriteLine( "Bye, have a good day" );
Мило)

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
> +    public void ReadFile( string filePath, Dictionary<string, string> englishToRussianDictionary, Dictionary<string, string> russianToEnglishDictionary )
Метод называется ReadFile, но зачем-то помимо пути мы передаём две переменные englishToRussianDictionary и russianToEnglishDictionary. 

Если я захочу воспользоваться функционалом этого класса то войду в замешательство т.к. чтобы считать данные из файла мне нужно будет передавать какие-то непонятные переменные. Название метода слишком общее, может следовало назвать ReadDictionaryFile?

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
> +    private void PopulateDictionaries( string[] lines, Dictionary<string, string> englishToRussianDictionary, Dictionary<string, string> russianToEnglishDictionary )
Обычно когда подразумевается, что в методе будет заполняться сущность, которая передается в аргументе, то вместо слова Populate следует использовать слово Fill :)

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
> +            Console.WriteLine( $"Error reading file: {ex.Message}" );
Круто что обрабатываешь ошибки при считывании файла!

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/InputValidator.cs
> +    private Dictionary<string, string> russianToEnglishDictionary;
Приватные поля принято начинать с нижнего подчёркивание "_russianToEnglishDictionary"

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/InputValidator.cs
> +
Лишний отступ

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
> +﻿public class FileReader
Если класс реализует только логику работы с файлом словаря то может стоит его назвать по другому? Название слишком общее, как будто должен уметь считывать любой файл, тут надо немного конкретизировать :)

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
> +            string[] parts = line.Split( ':' );
не понятно что в себе хранит parts, о каких частях идёт речь? Может words?

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/InputValidator.cs
> +    public bool ValidateInput( string userInput, out string errorMessage )
dir: дальше вместо out можно будет просто возвращать кастомный тип, у которого будут поля 
errorMessage 
isSucces

Но это потом :)

2024-03-31 16:27 UTC, Nafanyan commented on RusEngTranslator/Program.cs
> +        }
dir: Можно что-то вроде 
if ( englishToRussianDictionary.ContainsKey( wordToTranslate ) )
        {
            string russianTranslation = englishToRussianDictionary[ wordToTranslate ];
            Console.WriteLine( $"{wordToTranslate} in Russian is {russianTranslation}" );
            return;
        }
        
И по похожему принципу остальные условия, а else вообще убрать, почему это будет работать можешь подумать и написать)

2024-04-01 07:42 UTC, RedkeyD commented on RusEngTranslator/Program.cs
> +        }
а, также и было сделано, разве нет или я что то не понял)

2024-04-01 07:53 UTC, RedkeyD commented on RusEngTranslator/InputValidator.cs
> +    public bool ValidateInput( string userInput, out string errorMessage )
А можно примерно посмотреть как это реализовано где нибудь :)

2024-04-02 09:56 UTC, Nafanyan approved these changes
Мне всё нравится, чисто, аккуратно, раскидано по классам. С документацией ты конечно заморочился, но думаю достаточно описывать просто класс (что он делает) и методы (что они делают). Ставлю апрув, исправь только небольшие недочёиы)

2024-04-02 09:56 UTC, Nafanyan commented on RusEngTranslator/Program.cs
> +        }
Не, тогда бы это выглядело так)

if ( englishToRussianDictionary.ContainsKey( wordToTranslate ) )
        {
            string russianTranslation = englishToRussianDictionary[ wordToTranslate ];
            Console.WriteLine( $"{wordToTranslate} in Russian is {russianTranslation}" );
            return;
        }
if ( russianToEnglishDictionary.ContainsKey( wordToTranslate ) )
        {
            string englishTranslation = russianToEnglishDictionary[ wordToTranslate ];
            Console.WriteLine( $"{wordToTranslate} на английском это {englishTranslation}" );
            return;
        }

Console.WriteLine( $"Translation not found for '{wordToTranslate}'" );

2024-04-02 09:56 UTC, Nafanyan commented on RusEngTranslator/Program.cs
> +    static void TranslationLoop(Translator translator)
Пробелы в скобочках)

2024-04-02 09:56 UTC, Nafanyan commented on RusEngTranslator/Translator.cs
> +    public Translator(string filePath)
пробелы в скобках)

2024-04-02 09:56 UTC, Nafanyan commented on RusEngTranslator/Translator.cs
> +        catch(FileNotFoundException)
пробелы в скобках)

2024-04-02 09:56 UTC, Nafanyan commented on RusEngTranslator/InputValidator.cs
> +    public bool ValidateInput( string userInput, out string errorMessage )
Что-то типа такого)
https://github.com/Nafanyan/WebCalendar/blob/main/Application/Validation/ValidationResult.cs

2024-04-02 10:45 UTC, RedkeyD commented on RusEngTranslator/Program.cs
> +        }
Ааа, понятно, да там else и правда лишний и читать так удобней, спасибо за совет)

2024-04-02 10:55 UTC, RedkeyD commented
все пробелы были поставлены)

2024-04-03 06:02 UTC, Nafanyan approved these changes

2024-04-05 11:27 UTC, merged