Added Fighters game for review
Zievidinov/Travelline_practice pull request #3
Opened 2024-03-29 07:49 UTC by RedkeyD

2024-03-31 18:28 UTC, Nafanyan requested changes
В целом минимум выполнен, поправь если не прав, не сделано:
* Добавить механизм, при котором урон может меняться по рандому в каком-то диапазоне, например, в диапазоне от -20% до +10%
* Добавить возможность критического урона
* Добавить механизм инициативы
* Добавить возможность игры с нексколькими бойцами (желательно перед этим сделать инициативу)

Некоторые классы выполняют не свою работу, плюс комменты по форматированию, будут вопросы пиши, тг @nafanyann

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/Messages.cs
> +    public string CreateFighterNameMessage { get; } = "Enter your fighter name, Milord: ";
Лучше между каждым сообщением сделать отступ и использовать константы т.к. текст у нас вряд ли поменяется.

Так же не думаю что в каждой переменной нужно окончание "Message" ведь ты при обращении будешь получать их через класс Messages, который подразумевает что хранит в себе сообщения)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/Messages.cs
> +﻿namespace Fighters;
точно такой namespace?

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +namespace Fighters;
точно такой namespace?

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +internal class UI
internal использовать не так уж плохо, но сейчас получается мешанина из разных модификаторов доступа, где-то public, а где-то internal. Если объяснишь зачем здесь internal то можно оставить)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +
пустая строка

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +    private IArmor ChooseQualityOfArmor( string qualityOfArmor )
Попробуй это вынести в отдельный класс с окончание fabric и поместить его в директорию со Armor'ами. Может сложиться ситуация что у тебя будет новый UI, не консольный а графический и тогда тебе придётся дублировать этот код например в GraphicUI. Тем более это логика выбора класса по названию и она немного не соответствует логике UI'а )

Так же если у тебя появится новый armor (никогда не знаешь когда придётся дополнить существующий функционал) то всё что тебе нужно будет сделать это создать класс и добавить условие в фабрику, которая лежит в этой же директории, весьма удобно)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +    private IWeapon ChooseQualityOfWeapon( string qualityOfWeapon )
Смотри коммент выше про ChooseQualityOfArmor

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +    private IRace ChooseRace( string race )
Смотри коммент выше про ChooseQualityOfArmor

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +    public void ClearUI()
Необязательно добавлять окончание UI, ведь это метод в рамках класса UI и подразумевается что он относится к UI

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Program.cs
> +        var firstFighter = new Fighter( ui.GetFighterName(), ui.GetFighterRace(), ui.GetFighterWeapon(), ui.GetFighterArmor() );
var firstFighter = new Fighter( 
            ui.GetFighterName(), 
            ui.GetFighterRace(), 
            ui.GetFighterWeapon(), 
            ui.GetFighterArmor() );

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Program.cs
> +        var secondFighter = new Fighter(ui.GetFighterName(), ui.GetFighterRace(), ui.GetFighterWeapon(), ui.GetFighterArmor() );
Аналогично с комментом выше

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Program.cs
> +        var master = new GameMaster();
master => gameMaster

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Program.cs
> +        var winner = master.PlayAndGetWinner( firstFighter, secondFighter );
var лучше не использовать в ситуациях, когда тип в правой части не очевиден. При инициализации переменных с использованием методов лучше использовать конкретные типы, в данном случае IFighter

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Program.cs
> +        Console.WriteLine( messages.FighterCreatedMessage );
Это по идее тоже относится к UI'ю))

Может в UI стоит добавить метод по выводу сообщения, передаваемого через аргумент?)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Program.cs
> +        UI ui = new UI();
nid Было бы классно создать интерфейс IUserInterface и от него реализовать ConsoleUI (твой текущий класс UI). Так в дальнейшем можно было бы легко добавить какой-нибудь GraphicsUI)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Program.cs
> +        Messages messages = new Messages();
Если использовать в Messages  константные поля то экземпляр не понадобится, можно будет обращаться к переменным через тип

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/GameMaster.cs
> +        opponent.TakeDamage(damage);
пробелы в скобочках, раз уже везде их используешь)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Models/Fighters/Fighter.cs
> +        if (CurrentHealth < 0)
пробелы в скобочках, раз уже везде их используешь)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/Models/Fighters/IFighter.cs
> +    public void TakeDamage(int damage);
пробелы в скобочках, раз уже везде их используешь)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +        return ChooseRace(race);
пробелы в скобочках, раз уже везде их используешь)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +        return ChooseQualityOfWeapon(qualityOfWeapon);
пробелы в скобочках, раз уже везде их используешь)

2024-03-31 18:28 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +
Пробелы между условиями switch лучше не ставить, если интересно как ещё можно написать эту конструкцию (синтаксический сахар), то можешь почитать:
https://metanit.com/sharp/tutorial/3.45.php?ysclid=lufuoqiht6395997914

2024-04-01 10:13 UTC, RedkeyD commented on FighterGame/Fighters/UI/UI.cs
> +internal class UI
из за того что этот UI написан  только для этого проекта и его нельзя использовать как обычную библиотеку, может быть?)

2024-04-02 11:40 UTC, Nafanyan commented on FighterGame/Fighters/UI/UI.cs
> +internal class UI
В данном случае да, можно выделять отдельные проекты для UI, но это уже совсем другая история)

2024-04-05 11:47 UTC, RedkeyD commented
Извиняюсь за первый раз, на лекции говорили только ui добавить, а саму дз я не читал, поэтому не знал что там были доп. условия. Но вроде сейчас все должно быть по дз :)

2024-04-06 19:08 UTC, Nafanyan requested changes
Очень хорошо, но надо исправить некоторые моменты. + похоже есть некоторое недопонимание использования полиморфизма в ООП. Реализовал критический урон. 

Нечестно сражаются бойцы, как будто при их нечетном количестве всегда будет побеждать последний, ведь он на последний бой выйдет целым, а его оппонент будет побитым)

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/Program.cs
> +        FighterConsoleUI fighterConsoleUI = new FighterConsoleUI();
Тогда у тебя IFighterUserUnterface не имеет смысла.

Идея полиморфизма в том, чтобы в программе можно было легко заменять реализации определённого функционала, т.к. они связаны одним интерфейсом, приведу пример на этой строчке кода.

FighterConsoleUI fighterConsoleUI = new FighterConsoleUI();
Если ты захочешь в программе заменить использование консольного UI'я на графический то тебе придётся создавать новую переменную и заменять старую переменную на новую:
~~FighterConsoleUI fighterConsoleUI = new FighterConsoleUI();~~
FighterGraphicUI fighterGraphicUI = new FighterGraphicUI();

 ~~int numOfFighters = fighterConsoleUI.GetNumInput( Messages.AskNumOfFighters );~~
int numOfFighters = **fighterGraphicUI**.GetNumInput( Messages.AskNumOfFighters );

~~List<IFighter> fighters = fighterConsoleUI.CreateFighters( numOfFighters );~~
List<IFighter> fighters = **fighterGraphicUI**.CreateFighters( numOfFighters );

~~fighterConsoleUI.DetailsOfFighters( fighters );~~
**fighterGraphicUI**.DetailsOfFighters( fighters );

Подумай над тем какие методы тебе действительно нужны в интерфейсе IFighterUserUnterface потому как ты должен создать переменную типа IFighterUserUnterface и положить в неё конкретную реализацию:
IFighterUserUnterface fighterUI = new FighterConsoleUI();

Тогда когда тебе нужно будет поменять реализацию с консольной на графическую ты просто заменишь правую часть строки:
IFighterUserUnterface fighterUI = new FighterGraphicUI();

И дальше в программе всё будет работать также как и до этого

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/UI/IFighterUserUnterface.cs
> +    string GetName();
Эти методы используются только в классе реализации (FighterConsoleUI). За пределами FighterConsoleUI, который реализовывает этот интерфейс, они не выходят поэтому:
1. Может сделать их protected;
2. Подумай, а действительно ли они нужны.

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/UI/FighterConsoleUI.cs
> +namespace Fighters;
а может namespace Fighters.UI?

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/UI/Messages.cs
> +﻿namespace Fighters;
а может namespace Fighters.UI?

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/GameMaster.cs
> +public class GameMaster
Было бы здорово в конструктор GameMaster передавать IFighterUserUnterface и использовать его методы для вывода информации вместо Consile.WriteLine() и т.д.

Было бы странно если бы ты решил использовать графический интерфейс, но при выполнении методов GameMaster информация у тебя выводилась бы в консоль)

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/GameMaster.cs
> +        if ( IsCriticalHit() )
Ееее, шанс критического урона)

Круто было бы если процент шанса зависел от оружия (либо другой характеристики), а не от постоянного значение в 10% для каждого)

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/Models/Fighters/Fighter.cs
> +
лишняя строка)

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/Models/Fighters/Fighter.cs
> +
Лишняя строка)

2024-04-06 19:08 UTC, Nafanyan commented on Fighters/Fighters/Models/Fighters/IFighter.cs
> +    public string Name { get; }
Интересно ты отделил Name от всех, по моему можно отнести к верхней группе, т.е. верхнюю пустую строку можно убрать

2024-04-10 09:58 UTC, RedkeyD commented on Fighters/Fighters/UI/IFighterUserUnterface.cs
> +    string GetName();
сделал их приватными и убрал из интерфейса, стала вглядить лучше структура)

2024-04-10 09:59 UTC, RedkeyD commented on Fighters/Fighters/GameMaster.cs
> +    public IFighter PlayAndGetWinner( List<IFighter> fighters )
исправил, теперь каждый должен атаковать каждого рандомно

2024-04-10 10:14 UTC, RedkeyD commented on Fighters/Fighters/GameMaster.cs
> +public class GameMaster
было сделано, только я не уверен все ли правильно, я прочитал про это, меня отправило на реализацию Logger, сделал более менее как понял)

2024-04-10 10:15 UTC, RedkeyD commented on Fighters/Fighters/GameMaster.cs
> +        if ( IsCriticalHit() )
да, было добавлено Property CriticalHitChance интерфейс оружия)

2024-04-10 10:16 UTC, RedkeyD commented on Fighters/Fighters/Program.cs
> +        FighterConsoleUI fighterConsoleUI = new FighterConsoleUI();
было исправлено, да, я там и правда немного запутался, спасибо что сказал)

2024-04-10 14:38 UTC, Nafanyan requested changes

2024-04-10 14:38 UTC, Nafanyan commented on Fighters/Fighters/UI/FighterConsoleUI.cs
> +        string fighterArmor = Input( Messages.AvailableArmors );
Я упорно пытался ввести цифры, но он даже ничего мне не сказал (просто собрал мне дефолтного война), оказывается нужно было писать текстом: helmet, breastplate или gauntlets. Давай подумаем как можно облегчить жизнь пользователю и сделать чтобы он вводил цифры)

2024-04-10 14:38 UTC, Nafanyan commented on Fighters/Fighters/GameMaster.cs
> +            fighters.RemoveAll( fighter => fighter.CurrentHealth < 1 );
Из-за того что проверка на выбывших бойцов стоит здесь случилось бесчинство!
Боец num_2 умер в прошлом раунде, но бойца num_3 это не смутило, он вызвал на бой бойца у которого 0 хп и получил от 112 дамага от бойца, который погиб (черная магия не иначе). Как итог все бойцы мертвы))))

![image](https://github.com/RedkeyD/Travelline_practice/assets/90004716/1fea7169-4dd7-4b45-b502-99f55e555a00)

И сработанное исключение, которое сломало программу))
![image](https://github.com/RedkeyD/Travelline_practice/assets/90004716/22857e87-26f7-4bf4-8db0-fa94d61fc5d0)

2024-04-10 14:38 UTC, Nafanyan commented on Fighters/Fighters/GameMaster.cs
> +        return fighters[ 0 ];
Здесь у тебя получается пустой fighters и при обращении к нулевому элементу программа ломается (см. коммент выше)

2024-04-10 14:38 UTC, Nafanyan commented on Fighters/Fighters/Program.cs
> +        GameMaster gameMaster = new GameMaster( random, fighterConsoleUI );
random можно создавать в конструкторе класса GameMaster и не передавать его здесь)

2024-04-10 14:38 UTC, Nafanyan commented on Fighters/Fighters/Models/Weapons/Axe.cs
> +    public string Name { get; } = "Axe";
почему где-то между полями есть пустые строки, а где-то нет)

Приведи к единому стилю

2024-04-10 14:38 UTC, Nafanyan commented on Fighters/Fighters/GameMaster.cs
> +
лишняя пустая строка

2024-04-10 14:38 UTC, Nafanyan commented on Fighters/Fighters/GameMaster.cs
> +
лишняя пустая строка

2024-04-15 14:07 UTC, Nafanyan approved these changes

2024-04-15 21:39 UTC, merged