Added Debug for review
Zievidinov/Travelline_practice pull request #5
Opened 2024-04-12 23:09 UTC by RedkeyD

2024-04-22 06:02 UTC, Nafanyan requested changes

2024-04-22 06:02 UTC, Nafanyan commented on RusEngTranslator/FileReader.cs
Ненужные изменения в ПРе)

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/fixes.txt
> +﻿ AccommodationsProcessor:
ох ёмае, думаю лучше было бы написать это на русском, т.к. этот файл для проверяющих)

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +                ProcessBookCommand( parts );
Решил раскидать на отдельные функции, неплохо!

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +            return false;
Попробуй здесь убрать return false и вместо 
Console.WriteLine( $"Invalid {dateType} date format: {dateString}" ); 
написать  throw new ArgumentException( $"Invalid {dateType} date format: {dateString}" ); 

Это исключение будет пробрасываться выше и ловиться блоком catch, аналогично с другими валидациями)

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +        if ( DateTime.Parse( parts[ 3 ] ) > DateTime.Parse( parts[ 4 ] ) )
Получается так, что одну дату парсишь два раза, первый раз в ValidateDate, второй раз тут. Попробуй в ValidateDate возвращать либо Null в зависимости от того валидная дата или нет, либо воспользоваться параметром out

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +            Console.WriteLine( "Invalid arguments for 'find'. Expected format: 'find <BookingId>'" );
лучше выбрасывай throw, а в блоке обработки ошибок catch уже решишь как отображать ошибку. Если ты захочешь отображать ошибку в виде всплывающего окна, а не вывода в консоль, то придётся перелопачивать весь код)

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +        if ( !ValidateDate( parts[ 3 ], "start" ) )
лучше всегда использовать фигурные скобочки 
if ( !ValidateDate( parts[ 3 ], "start" ) )
{
return;
}

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +
лишняя строка

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/BookingService.cs
> +
Ещё нужна проверка на то, совпадает ли дата въезда и выезда
![image](https://github.com/RedkeyD/Travelline_practice/assets/90004716/4a8c7528-4bd9-450a-9c8a-2782ae308874)

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/BookingService.cs
> +        if ( booking.StartDate <= DateTime.Now )
Бронирование нельзя отменить в день заезда

2024-04-22 06:02 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/BookingService.cs
> +        return totalCost;
Как будто рассчитывается немножко неправильно, подумай над тем, правильно ли ты работаешь с валютой
![image](https://github.com/RedkeyD/Travelline_practice/assets/90004716/d2529ca6-191a-42a7-96a2-519f44527de3)

2024-05-06 07:10 UTC, Nafanyan requested changes

2024-05-06 07:10 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/fixes.txt
> + https://docs.google.com/document/d/151YY4UDh0vfuzOGDxaLSMWEQLtTxt3KMPb9_HmzURP0/edit?addon_store
Открой доступ)

2024-05-06 07:10 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/BookingService.cs
> +
Здесь не должна быть проверка на то что мы можем отменить бронь только если она ещё не наступила if (booking.StartDate < DateTime.Now)?

2024-05-06 07:10 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/BookingService.cs
> +
Здесь не должна быть проверка на то что мы можем отменить бронь только если она ещё не наступила if (booking.StartDate < DateTime.Now)?

2024-05-06 07:10 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +        do
можно так while ((input = Console.ReadLine()) != "exit"), так даже лучше читается)

В случае если введут exit то программа из цикла сразу выйдет, что логично. При do while она пройдёт по телу цикла хотя бы 1 раз. Т.е. если мы первый раз введём exit то пройдёмся по телу цикла, что не очень логично

2024-05-06 07:10 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +        string strCurrency = commandParts[ 5 ];
Нужна проверка на размер массива, я ввёл "book 1 1" и оно сломалось)

2024-05-08 11:02 UTC, RedkeyD commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +        string strCurrency = commandParts[ 5 ];
да, там случайно убрал проверку на количество аргументов, теперь обратно вернул

2024-05-08 11:02 UTC, Zievidinov commented on Debug/Accomodations/Accommodations/fixes.txt
> + https://docs.google.com/document/d/151YY4UDh0vfuzOGDxaLSMWEQLtTxt3KMPb9_HmzURP0/edit?addon_store
открыл) вроде

2024-05-08 11:03 UTC, RedkeyD commented on Debug/Accomodations/Accommodations/BookingService.cs
> +
я кстати немного не понял зачем нам проверка там, поэтому убрал

2024-05-08 11:03 UTC, Zievidinov commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +        do
исправил как было изначально)

2024-05-08 11:04 UTC, RedkeyD commented on Debug/Accomodations/Accommodations/BookingService.cs
> +
добавил

2024-05-11 07:29 UTC, Nafanyan approved these changes
Можешь мержить, но)

1. Раскидай в корне директории по homework1/ и т.д.
2. У тебя две мастер ветки Master по моему лишний)

2024-05-11 07:29 UTC, Nafanyan commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +        string command, exit = "exit";
exit объявил, но нигде не используешь)

2024-05-17 09:58 UTC, RedkeyD commented on Debug/Accomodations/Accommodations/AccommodationsProcessor.cs
> +        string command, exit = "exit";
ага, сейчас поправлю и смержу, вообще без понятия почему там Мастер ветка, когда я пуш сделал на мастер, но просто удалил ветку. Так и без понятия почему она там появилась

2024-05-17 10:28 UTC, merged