Added DB for review
Zievidinov/Travelline_practice pull request #6
Opened 2024-04-13 00:26 UTC by RedkeyD

2024-05-11 08:36 UTC, Nafanyan commented
У тебя опять много лишнего в ПРе, предлагаю обсудить гит политику)

2024-05-11 08:54 UTC, Nafanyan requested changes
попробуй полностью снести всё и по этим скриптам с нуля всё воссоздать)

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Inserts.sql
> +INSERT INTO dbo.Rooms (room_id, room_number, room_type, price_per_night, availability)
room_id тебе заполнять не надо, он должен заполняться автоматически т.к. ты прописал IDENTITY(1,1). Аналогично и с другими первичными ключами)

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Inserts.sql
> +(2, '�����������'),
Чтобы можно было писать по русски добавь перед добавляй N, N'Супер мега мягкая кровать'

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Tables.sql
> +IF NOT EXISTS ( SELECT * FROM sysobjects WHERE name ='Customers')
где то есть пробела в скобках, где-то нет, лучше привести к единому стилю)

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Tables.sql
> +	CREATE TABLE dbo.Rooms(
лучше уж так)
```sql
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Rooms')
	CREATE TABLE dbo.Rooms(
		room_id INT IDENTITY(1,1) NOT NULL,
		room_number INT NOT NULL,
		room_type NVARCHAR(50) NOT NULL,
		price_per_night MONEY NOT NULL,
		availability BIT NOT NULL,
		CONSTRAINT PK_rooms_id_room PRIMARY KEY(room_id)
	)
```

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Tables.sql
> +	 facility_name NVARCHAR(200) NOT NULL,
200 как будто много для названия)

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Queries.sql
> +    WHERE check_in_date <= GETDATE()
два раза рассчитываешь GETDATE(), попробуй через between и один раз расчитывать

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Queries.sql
> +    WHERE first_name = '���' OR email = 'email@example.com'
для корректного отображения русских символов в одинарных скобочках ставь перед ними N

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Queries.sql
> +WHERE room_id = 1;
мы скорее всего знаем номер комнаты, а не её id, проще говоря room_number, а не room_id. Тут подумай как объединить две таблицы)

2024-05-11 08:54 UTC, Nafanyan commented on Backend/SQL/HotelManagement/Queries.sql
> +    WHERE check_in_date <= '2024-04-15' AND check_out_date >= '2024-04-15'
можно и так, а можно использовать оператор between)

Подсказка: только будет ли доступен твой номер?

2024-05-23 12:09 UTC, Zievidinov commented on Backend/SQL/HotelManagement/Inserts.sql
> +INSERT INTO dbo.Rooms (room_id, room_number, room_type, price_per_night, availability)
автоматически генерировал, не обратил внимание что там даже первичный ключ генерировался)

2024-06-03 05:25 UTC, Nafanyan approved these changes
гуд гуд гуд)))

2024-06-03 05:25 UTC, Nafanyan commented on Backend_practice/homework4/SQL/HotelManagement/Queries.sql
> +SELECT *
давай только Select и From на одной строке сделаем)

2024-06-03 05:25 UTC, Nafanyan commented on Backend_practice/homework4/SQL/HotelManagement/Queries.sql
> +WHERE last_name LIKE 'S%';
👍

2024-06-03 05:25 UTC, Nafanyan commented on Backend_practice/homework4/SQL/HotelManagement/Queries.sql
> +SELECT b.*
👍

2024-06-03 05:51 UTC, merged